language: node_js
node_js:
  - "14"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - develop

install:
  - npm install -g pnpm
  - pnpm install
  - pnpm run build

script:
  - echo "Nothing to test"

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: .vitepress/dist
  on:
    branch: master
